import { useLocation, useNavigate } from 'react-router-dom';
import { ArrowLeft, Shield } from 'lucide-react';

export default function PolicyPage() {
  const navigate = useNavigate();
  const location = useLocation();
  const type = location.pathname.substring(1); // Remove leading slash
  
  const policies = {
    privacy: {
      title: 'Privacy Policy',
      content: [
        {
          heading: 'Data Collection',
          text: 'NIRF Compass operates entirely within your browser. We do not collect, transmit, or store any personal data on external servers. All analysis data is stored locally in your browser using localStorage.',
        },
        {
          heading: 'Local Storage',
          text: 'Your university analyses and search history are stored locally on your device. This data persists across sessions but remains entirely under your control. You can clear this data at any time through the Search History page or by clearing your browser data.',
        },
        {
          heading: 'No Tracking',
          text: 'We do not use cookies, analytics, or tracking technologies. Your usage of this platform is completely private.',
        },
        {
          heading: 'Data Security',
          text: 'Since all data is stored locally, security depends on your device and browser security. We recommend using updated browsers and maintaining device security best practices.',
        },
      ],
    },
    terms: {
      title: 'Terms of Use',
      content: [
        {
          heading: 'Academic Purpose',
          text: 'NIRF Compass is an academic research platform designed for strategic planning and educational purposes. It is not an official NIRF submission or ranking tool.',
        },
        {
          heading: 'No Warranties',
          text: 'The platform provides strategic recommendations based on analytical models. We make no warranties about the accuracy, completeness, or suitability of the analysis for any particular purpose.',
        },
        {
          heading: 'User Responsibility',
          text: 'Users are responsible for validating recommendations with official institutional data and consulting with appropriate academic leadership before implementing any suggested changes.',
        },
        {
          heading: 'Intellectual Property',
          text: 'The NIRF Compass platform, including its design, code, and methodology, is the intellectual property of CSPIT AIML Department, CHARUSAT.',
        },
      ],
    },
    'data-policy': {
      title: 'Data Usage Policy',
      content: [
        {
          heading: 'Data Processing',
          text: 'All data processing occurs locally in your browser. University names entered are used solely to generate analytical assessments and are not transmitted to any external servers.',
        },
        {
          heading: 'Generated Reports',
          text: 'PDF reports generated by the system are created locally and downloaded directly to your device. We have no access to these reports.',
        },
        {
          heading: 'Data Retention',
          text: 'Analysis history is retained in your browser localStorage until you manually delete it or clear your browser data. We do not have access to or control over this data.',
        },
        {
          heading: 'Third-Party Services',
          text: 'This platform does not integrate with third-party services or APIs that would have access to your data.',
        },
      ],
    },
    'ai-transparency': {
      title: 'AI Transparency Statement',
      content: [
        {
          heading: 'AI Methodology',
          text: 'NIRF Compass uses algorithmic analysis to generate performance assessments. The system employs deterministic algorithms based on institutional name patterns and predefined scoring models.',
        },
        {
          heading: 'Score Generation',
          text: 'Scores are generated using a combination of database lookups for known institutions and algorithmic generation for others. The system aims to produce realistic, educationally-relevant assessments.',
        },
        {
          heading: 'Limitations',
          text: 'The AI system does not have access to real-time institutional data, official NIRF submissions, or verified performance metrics. All assessments are simulated for strategic planning purposes.',
        },
        {
          heading: 'Recommendation Logic',
          text: 'Strategic recommendations are generated based on performance gaps identified through benchmark comparisons. The system uses rule-based logic to prioritize improvement areas.',
        },
        {
          heading: 'Human Oversight',
          text: 'This system is designed to support, not replace, human decision-making. All recommendations should be reviewed by qualified academic professionals before implementation.',
        },
      ],
    },
  };
  
  const policy = policies[type] || policies.privacy;
  
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <button
        onClick={() => navigate(-1)}
        className="flex items-center space-x-2 text-primary hover:text-primary-dark mb-8"
      >
        <ArrowLeft className="w-4 h-4" />
        <span>Back</span>
      </button>
      
      <div className="card">
        <div className="flex items-center space-x-3 mb-6">
          <div className="bg-primary/10 p-3 rounded-lg">
            <Shield className="w-6 h-6 text-primary" />
          </div>
          <h1 className="text-3xl font-bold text-gray-900">{policy.title}</h1>
        </div>
        
        <div className="space-y-6">
          {policy.content.map((section, index) => (
            <div key={index}>
              <h2 className="text-xl font-semibold text-gray-900 mb-3">
                {section.heading}
              </h2>
              <p className="text-gray-600 leading-relaxed">{section.text}</p>
            </div>
          ))}
        </div>
        
        <div className="mt-8 pt-6 border-t border-gray-200">
          <p className="text-sm text-gray-500">
            Last Updated: February 2026
          </p>
          <p className="text-sm text-gray-500 mt-2">
            For questions about this policy, please contact us through the Contact page.
          </p>
        </div>
      </div>
    </div>
  );
}
