import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { toast } from 'react-toastify';
import { Mail, Phone, MapPin, ChevronDown } from 'lucide-react';
import { motion } from 'framer-motion';
import { cn } from '@/utils/cn';

export default function ContactPage() {
  const { register, handleSubmit, formState: { errors }, reset } = useForm();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [openFaq, setOpenFaq] = useState(null);
  
  const onSubmit = async (data) => {
    setIsSubmitting(true);
    
    // Simulate form submission
    await new Promise(resolve => setTimeout(resolve, 1500));
    
    console.log('Form submitted:', data);
    toast.success('Message sent successfully! We will get back to you soon.');
    reset();
    setIsSubmitting(false);
  };
  
  const contactInfo = [
    {
      icon: Mail,
      title: 'Email',
      content: 'nirfcompass@cspit.edu',
      link: 'mailto:nirfcompass@cspit.edu',
    },
    {
      icon: Phone,
      title: 'Phone',
      content: '+91 (0) 2697-247000',
      link: 'tel:+912697247000',
    },
    {
      icon: MapPin,
      title: 'Address',
      content: 'CSPIT, CHARUSAT Campus, Changa, Gujarat 388421',
      link: null,
    },
  ];
  
  const faqs = [
    {
      question: 'How accurate is the AI analysis?',
      answer: 'Our AI system uses sophisticated algorithms to generate realistic performance assessments based on institutional data patterns. While highly analytical, results should be validated with official institutional data for strategic planning purposes.',
    },
    {
      question: 'Can I analyze multiple universities?',
      answer: 'Yes! You can analyze as many universities as needed. All analyses are saved in your Search History for easy access and comparison.',
    },
    {
      question: 'Is the generated report official?',
      answer: 'No. The reports generated by NIRF Compass are strategic advisory documents for internal planning purposes. They are not official NIRF submissions or rankings.',
    },
    {
      question: 'How is my data stored?',
      answer: 'Analysis data is stored locally in your browser using secure local storage. We do not transmit or store your data on external servers.',
    },
    {
      question: 'Can I customize the recommendations?',
      answer: 'Currently, recommendations are generated automatically based on performance analysis. Future versions may include customization options.',
    },
    {
      question: 'What format is the report available in?',
      answer: 'Reports are available as professionally formatted PDF documents that can be downloaded and shared with stakeholders.',
    },
  ];
  
  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      {/* Header */}
      <div className="text-center mb-12">
        <motion.h1
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-4xl md:text-5xl font-bold text-gray-900 mb-4"
        >
          Contact Us
        </motion.h1>
        <motion.p
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="text-xl text-gray-600"
        >
          Have questions? We're here to help
        </motion.p>
      </div>
      
      <div className="grid lg:grid-cols-2 gap-12 mb-16">
        {/* Contact Form */}
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          className="card"
        >
          <h2 className="text-2xl font-bold text-gray-900 mb-6">Send us a Message</h2>
          
          <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">
                Full Name
              </label>
              <input
                type="text"
                {...register('name', {
                  required: 'Name is required',
                  minLength: { value: 2, message: 'Name must be at least 2 characters' },
                })}
                className="input-field"
                placeholder="Enter your full name"
              />
              {errors.name && (
                <p className="text-red-600 text-sm mt-1">{errors.name.message}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">
                Email Address
              </label>
              <input
                type="email"
                {...register('email', {
                  required: 'Email is required',
                  pattern: {
                    value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
                    message: 'Invalid email address',
                  },
                })}
                className="input-field"
                placeholder="your.email@example.com"
              />
              {errors.email && (
                <p className="text-red-600 text-sm mt-1">{errors.email.message}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">
                Subject
              </label>
              <input
                type="text"
                {...register('subject', {
                  required: 'Subject is required',
                })}
                className="input-field"
                placeholder="What is this regarding?"
              />
              {errors.subject && (
                <p className="text-red-600 text-sm mt-1">{errors.subject.message}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">
                Message
              </label>
              <textarea
                {...register('message', {
                  required: 'Message is required',
                  minLength: { value: 10, message: 'Message must be at least 10 characters' },
                })}
                rows={5}
                className="input-field resize-none"
                placeholder="Tell us more about your inquiry..."
              />
              {errors.message && (
                <p className="text-red-600 text-sm mt-1">{errors.message.message}</p>
              )}
            </div>
            
            <button
              type="submit"
              disabled={isSubmitting}
              className="btn-primary w-full"
            >
              {isSubmitting ? 'Sending...' : 'Send Message'}
            </button>
          </form>
        </motion.div>
        
        {/* Contact Information */}
        <motion.div
          initial={{ opacity: 0, x: 20 }}
          animate={{ opacity: 1, x: 0 }}
          className="space-y-6"
        >
          <div className="card">
            <h2 className="text-2xl font-bold text-gray-900 mb-6">Get in Touch</h2>
            
            <div className="space-y-4">
              {contactInfo.map((info, index) => (
                <div key={index} className="flex items-start space-x-4">
                  <div className="bg-primary/10 p-3 rounded-lg flex-shrink-0">
                    <info.icon className="w-5 h-5 text-primary" />
                  </div>
                  <div>
                    <h3 className="font-semibold text-gray-900 mb-1">{info.title}</h3>
                    {info.link ? (
                      <a
                        href={info.link}
                        className="text-gray-600 hover:text-primary transition-colors"
                      >
                        {info.content}
                      </a>
                    ) : (
                      <p className="text-gray-600">{info.content}</p>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
          
          <div className="card bg-blue-50 border-2 border-blue-200">
            <h3 className="text-lg font-bold text-blue-900 mb-3">Project Information</h3>
            <div className="text-sm text-blue-800 space-y-2">
              <p><span className="font-semibold">Department:</span> Artificial Intelligence & Machine Learning</p>
              <p><span className="font-semibold">Institution:</span> CSPIT, CHARUSAT</p>
              <p><span className="font-semibold">Project Type:</span> Academic Research Platform</p>
              <p><span className="font-semibold">Year:</span> 2026</p>
            </div>
          </div>
        </motion.div>
      </div>
      
      {/* FAQ Section */}
      <div className="max-w-4xl mx-auto">
        <h2 className="text-3xl font-bold text-center text-gray-900 mb-8">
          Frequently Asked Questions
        </h2>
        
        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.05 }}
              className="card"
            >
              <button
                onClick={() => setOpenFaq(openFaq === index ? null : index)}
                className="w-full flex items-center justify-between text-left"
              >
                <h3 className="text-lg font-semibold text-gray-900 pr-4">
                  {faq.question}
                </h3>
                <ChevronDown
                  className={cn(
                    'w-5 h-5 text-gray-400 transition-transform flex-shrink-0',
                    openFaq === index && 'transform rotate-180'
                  )}
                />
              </button>
              
              {openFaq === index && (
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: 'auto' }}
                  exit={{ opacity: 0, height: 0 }}
                  className="mt-4 pt-4 border-t border-gray-200"
                >
                  <p className="text-gray-600">{faq.answer}</p>
                </motion.div>
              )}
            </motion.div>
          ))}
        </div>
      </div>
    </div>
  );
}
